tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "heroku/brew"

brew "awscli"
brew "exa"
brew "git"
brew "heroku/brew/heroku"
brew "htop"
brew "jq"
brew "mas"
brew "mitmproxy"
brew "pandoc"
brew "poetry"
brew "pyenv"
brew "shellcheck"
brew "starship"
brew "trash"
brew "watch"
brew "wifi-password"
brew "youtube-dl"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"

cask "backblaze"
cask "cleanshot"
cask "discord"
cask "docker"
cask "downie"
cask "font-caskaydia-cove-nerd-font"
cask "font-iosevka"
cask "forecast"
cask "gpg-suite"
cask "grandperspective"
cask "handbrake"
cask "hex-fiend"
cask "imageoptim"
cask "insomnia"
cask "iterm2"
cask "itsycal"
cask "launchcontrol"
cask "little-snitch"
cask "netnewswire"
cask "obs"
cask "obsidian"
cask "owasp-zap"
cask "Postgres"
cask "sf-symbols"
cask "signal"
cask "sketch"
cask "tableplus"
cask "tailscale"
cask "the-unarchiver"
cask "tower"
cask "transmission"
cask "transmit"
cask "visual-studio-code"
cask "whatsapp"
cask "yubico-authenticator"

mas "Core Data Lab", id: 1460684638
mas "Deliveries", id: 290986013
mas "DevCleaner", id: 1388020431
mas "Pastebot", id: 1179623856
mas "Slack", id: 803453959
mas "Soulver", id: 1508732804
mas "Swift Playgrounds", id: 1496833156
mas "Things", id: 904280696
mas "Xcode", id: 497799835
