tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/fonts'

brew 'jq'
brew 'mas'
brew 'nmap'
brew 'tree'
brew 'awscli'
brew 'bash-completion'
brew 'git'
brew 'heroku-toolbelt'
brew 'watchman'
brew 'pyenv'
brew 'pyenv-virtualenv'

cask 'java'
brew 'android-sdk'

cask 'arduino'
cask 'arq'
cask 'atom'
cask 'burp-suite'
cask 'cyberduck'
cask 'docker'
cask 'font-inconsolata'
cask 'genymotion'
cask 'gitup'
cask 'gpgtools'
cask 'handbrake'
cask 'imageoptim'
cask 'iterm2'
cask 'licecap'
cask 'logmein-client'
cask 'mongodb'
cask 'ngrok'
cask 'paparazzi'
cask 'postgres'
cask 'postman'
cask 'robomongo'
cask 'screenflow'
cask 'sketch'
cask 'skitch'
cask 'slack'
cask 'spotify'
cask 'the-unarchiver'
cask 'transmission'
cask 'tunnelblick'
cask 'virtualbox'
cask 'vlc'
cask 'webtorrent'
cask 'wireshark'

mas 'Pixelmator', id: 407963104
mas 'Keynote', id: 409183694
mas 'Pages', id: 409201541
mas 'Numbers', id: 409203825
mas '1Password', id: 443987910
mas 'Navicat Premium Essentials', id: 466416967
mas 'Xcode', id: 497799835
